stages:
  - test
  - build
  - publish

variables:
  PYTHON_VERSION: "3.13"

default:
  image:
    name: ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-trixie-slim
    entrypoint: [""]

lint:
  stage: test
  script:
    - uv sync
    - uv run ruff check .

test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y ffmpeg
  script:
    - uv sync
    - uv run behave

.docker_job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  only:
    - tags
  before_script:
    - export FQIN=$FQIP:$(git describe --always --tags)

build:
  extends: .docker_job
  stage: build
  environment: production
  script:
    - docker build --target publish -t $FQIN .

publish:
  extends: .docker_job
  stage: publish
  environment: production
  script:
    - docker run -e UV_PUBLISH_TOKEN "$FQIN"
